#!/usr/bin/env fish

function die
   exit 483
end

echo git pulling...
git pull || die

# echo
# echo removing node_modules...
# rm -rf node_modules || die

echo
echo installing dependencies...
pnpm i -P || die

echo
echo building...
pnpm run build || die

echo
echo migrating database...
pnpx prisma migrate deploy --preview-feature || die

echo
echo starting...
pnpm start || die
